spring.application.name=WishList
spring.datasource.url=jdbc:mysql://localhost:3306/wishlist
spring.datasource.username=root
spring.datasource.password=3389Nady.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
